---
title: "BMS 225A workshop 2"
author: "Julia Caroline McBride"
Date created: 2023.10.12
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---
# Weather data analysis

```{r load library}
library(tidyverse)
```


```{r read in data}
sf_weather <- read.csv("../raw_data/sf_weather_2023.csv")

head(sf_weather)
colnames(sf_weather)
```

```{r subset the data}
select(sf_weather, DATE)

sf_weather %>%
  select(DATE)

```
```{r subset and split out data}

sf_weather_temp <- sf_weather %>% 
  select(c("DATE", "TMAX", "TMIN")) %>% 
  na.omit() %>% 
  separate(DATE, c("YEAR", "MONTH", "DAY"), sep = "-", remove = FALSE) %>% 
  filter(YEAR == "2021") %>% 
  mutate(TAVG = ((TMAX + TMIN) / 2)) %>% 
  group_by(MONTH) %>% 
  summarise(MAX_MO_TEMP = max(TAVG))
  

head(sf_weather_temp)
```
#at the top you are defining your data set, and naming it sf_weather_temp
#selecting specific data columns to show
#then taking the date information (YYYY-MM-DD) into seperate columns
#then filtering by year
#then taking the data for a certain year and mutating the data (doing math) and creating a new column 
```{r pLOTTING sf weather temp}
plot(sf_weather_temp)

```

```{r Applying functions}
yearly_subsetter <- function(year){
  year_subset <- sf_weather %>% 
    select(c("DATE", "TMAX", "TMIN")) %>% 
    na.omit() %>% 
    separate(DATE, c("YEAR", "MONTH", "DAY"), sep = "-", remove = FALSE) %>% 
    filter(YEAR == year) %>% 
    mutate(TAVG = ((TMAX + TMIN) / 2)) %>% 
    group_by(MONTH) %>% 
    summarise(MAX_MO_TEMP = max(TAVG))
  
  return(year_subset)
}
```


```{r apply function with loops, fig.height=6, fig.width=4}
for(my_year_var in c("1970", "1980", "1990", "2000")){
  plot(yearly_subsetter(year = my_year_var), main = my_year_var)
  
}

```

